### PR TITLE
Fix Deref on Buf with null pointer

### LINKED ISSUE #22: Rust 1.78 results in precondition check panic
After updating to rust 1.78, I started hitting a precondition check panic in my tests:
```
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:123:9
   3: core::panicking::panic_nounwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:156:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/intrinsics.rs:2799:21
   5: core::slice::raw::from_raw_parts
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/slice/raw.rs:98:9
   6: <libgssapi::util::Buf as core::ops::deref::Deref>::deref
             at /Users/abinford/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libgssapi-0.7.0/src/util.rs:239:18
   7: libgssapi::context::ClientCtx::step
             at /Users/abinford/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libgssapi-0.7.0/src/context.rs:789:16
```

After some quick checks I think this might because they started enforcing the value of `from_raw_parts` to be non-null even if it's empty, and `Buf::empty()` uses a null pointer:
```rust
impl Buf {
    pub(crate) fn empty() -> Buf {
        Buf(gss_buffer_desc {
            length: 0,
            value: ptr::null_mut(),
        })
    }
```

but then the check
```rust
            self.state = ClientCtxState::Complete;
            if out_tok.len() > 0 {
                Ok(Some(out_tok))
            } else {
                Ok(None)
            }
```
fails because `out_tok` is empty and fails the precondition after being derefenced:
```rust
impl Deref for Buf {
    type Target = [u8];

    fn deref(&self) -> &Self::Target {
        unsafe { slice::from_raw_parts(self.0.value.cast(), self.0.length as usize) }
    }
}
```

Just guessing, not 100% sure this is the exact issue.

### PR DESCRIPTION
**Pull request by Kimahriman**
Resolves #22 

Rust 1.78 added a check in `slice::from_raw_parts` to make sure the value is not null, even if the length is 0. So the check `out_tok.len() > 0` would fail for an empty buf on this precondition. Updated Buf Deref to use a `NonNull::dangling` as recommended by `from_raw_parts` if the value is null.

Also had to move some new updates behind a feature flag because they didn't exist on my Mac

### CODE REVIEW

File: libgssapi/src/credential.rs [hunk 1]
```diff
@@ -184,6 +187,7 @@ impl Cred {
         }
     }
 
+    #[cfg(feature = "s4u")]
     pub fn store(
```
Comment (Kimahriman) [inline libgssapi/src/credential.rs:191]: The things used in this function didn't exist on my Mac build of libgssapi-sys, so I assumed they were maybe supposed to be behind the same feature that's used in some othe r parts of this file.

File: libgssapi/src/util.rs [hunk 2]
```diff
@@ -236,13 +237,25 @@ impl Deref for Buf {
     type Target = [u8];
 
     fn deref(&self) -> &Self::Target {
-        unsafe { slice::from_raw_parts(self.0.value.cast(), self.0.length as usize) }
+        unsafe {
+            if self.0.value.is_null() {
```
Comment (estokes) [inline libgssapi/src/util.rs]: This should check that both the length is 0 and the value is null. If the length isn't 0 and the value is null then we would like slice::from_raw_parts to fail

File: libgssapi/src/util.rs [hunk 3]
```diff
@@ -236,13 +237,25 @@ impl Deref for Buf {
...
+        }
     }
 }
 
 impl DerefMut for Buf {
     fn deref_mut(&mut self) -> &mut Self::Target {
-        unsafe { slice::from_raw_parts_mut(self.0.value.cast(), self.0.length as usize) }
+        unsafe {
+            if self.0.value.is_null() {
+                slice::from_raw_parts_mut(NonNull::dangling().as_ptr(), 0)
```
Comment (estokes) [inline libgssapi/src/util.rs:258]: Same here

**Review by estokes — CHANGES_REQUESTED** [review]

File: libgssapi/src/util.rs (hunk 2 above)
Comment (Kimahriman) [reply libgssapi/src/util.rs]: Good call, added

File: libgssapi/src/util.rs (hunk 3 above)
Comment (Kimahriman) [reply libgssapi/src/util.rs:258]: Added

File: libgssapi/src/util.rs [hunk 4]
```diff
@@ -202,7 +203,11 @@ impl<'a> Deref for BufRef<'a> {
     type Target = [u8];
 
     fn deref(&self) -> &Self::Target {
-        unsafe { slice::from_raw_parts(self.0.value.cast(), self.0.length as usize) }
+        if self.0.value.is_null() && self.0.length == 0 {
+            &[]
```
Comment (Kimahriman) [inline libgssapi/src/util.rs:207]: Saw this used in a different deref, I guess if there's a lifetime you can return a reference to an empty slice

**Review by estokes — APPROVED** [review]

**Comment by tafia** [comment]
Hi, any idea when a new version can be released?
